org: sherly01
service: api-vision-artificial

provider:
  name: aws
  runtime: python3.9 
  memorySize: 1024
  timeout: 20
  iam:
    role: arn:aws:iam::453630683778:role/LabRole

functions:
  listar:
    handler: DetectarEtiquetas.lambda_handler
    events:
      - http:
          path: /images/etiquetas
          method: post
          cors: true
          integration: lambda
